AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: public.ecr.aws/s2p2n5l7/ghwf:latest
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          MY_ENV_VAR: my-value

Outputs:
  MyLambdaFunctionArn:
    Value: !Ref MyLambdaFunction
