AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app.zip
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          MY_ENV_VAR: my-value
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  MyLambdaFunctionArn:
    Value: !GetAtt MyLambdaFunction.Arn